# 服务端口号
server:
  port: 8003
  ceshi: aaa

datasource:
  url: 127.0.0.1:3306/ceshi

spring:
  application:
    name: microservice-order-purchase
  cloud:
    stream:
      bindings:
        #input是接收，注意这里不能再像前面一样写output了
        input:
          destination: stream-demo
          group: s1
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000

mybatis:
  type-aliases-package: com.itcodai.springcloud.entity
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.itcodai.springcloud.ordersso.dao: trace
# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/ #,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/,
  instance:
    instance-id: 订票服务-8003  # 人性化显示出服务的信息
    prefer-ip-address: true    # 访问路径可显示ip地址

# 使用actuator来展示项目的基本信息
info:
  author.name: shengwu ni
  app.name: microservice
  server.port: ${server.port}
  application.name: ${spring.application.name}

